# Generated by Django 4.1.5 on 2023-01-13 19:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cavalo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1fcea21c-e308-40a5-a606-c22fde0dc9ee'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1fcea21c-e308-40a5-a606-c22fde0dc9ee'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='stamp_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1fcea21c-e308-40a5-a606-c22fde0dc9ee'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stamp',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1fcea21c-e308-40a5-a606-c22fde0dc9ee'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1fcea21c-e308-40a5-a606-c22fde0dc9ee'), primary_key=True, serialize=False),
        ),
    ]
